## Main Library

In [5]:
# Reading Data & Visulization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 

# Data Preprocessing 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

from imblearn.over_sampling import SMOTE

# Building Model
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

# XGboost
import xgboost as xgb

# Reading Data

In [8]:
data = pd.read_csv(r"D:\Courses language programming\5_Machine Learning\Dataset For Machine Learning\Credit_card\creditcard.csv")
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [9]:
data.shape

(284807, 31)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [11]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [12]:
data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [13]:
data.Class.value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [14]:
legit = data[data.Class == 0]
fraud = data[data.Class == 1]

In [15]:
legit.shape , fraud.shape

((284315, 31), (492, 31))

In [16]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [17]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [18]:
data.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

# Under Sampling

#### Build Smaple Dataset Containing Similar Distribution of normal transactions and Fraudulent transactions

In [20]:
legit_sample = legit.sample(n=492)

In [21]:
new_data = pd.concat([legit_sample, fraud], axis=0)

In [22]:
new_data.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
87727,61812.0,-1.435676,0.412251,2.357627,0.339258,0.823730,0.130028,0.064209,-0.674154,-0.106415,...,0.736974,0.044479,-0.393210,0.242333,0.560759,-0.392868,0.024002,-0.193550,1.00,0
30233,35833.0,1.171958,-0.875933,0.383311,-0.365794,-1.165867,-0.760110,-0.360243,-0.229918,-0.542303,...,0.054472,0.015866,-0.141514,0.441022,0.535226,-0.258556,-0.004205,0.034538,125.00,0
26055,33890.0,1.144283,-0.712729,1.189572,0.772825,-1.555963,-0.238452,-0.893916,0.076931,-0.260611,...,-0.355159,-0.601153,0.038591,0.314217,0.218659,-0.400528,0.074595,0.053207,74.00,0
115346,73837.0,-0.866733,0.286020,1.586642,-1.767943,-0.706429,-0.193034,0.342794,-0.157041,-1.099956,...,-0.662565,-1.133742,0.288523,0.213901,-0.691433,0.988059,-0.063099,-0.048535,48.00,0
214226,139585.0,-1.035039,-1.767121,-1.764196,2.482560,-1.652377,1.499984,4.653933,-0.763442,-1.297831,...,0.794386,1.002456,2.172594,-0.566245,-0.524426,-0.305642,-0.177412,0.115598,1007.99,0
51135,44811.0,1.347177,-1.198647,0.276155,-1.322392,-1.397904,-0.582732,-0.850071,-0.146476,-1.896743,...,-0.142338,-0.148169,-0.002995,0.053096,0.306663,-0.177975,0.029292,0.028262,82.86,0
185239,126583.0,-1.993379,0.495124,0.713289,-0.311974,-1.083812,0.324192,0.383176,0.912154,-0.124358,...,-0.082742,-0.565225,0.250426,0.534174,0.377894,-0.425941,-0.150900,-0.288525,185.09,0
260480,159577.0,-2.077718,-0.302558,-0.497414,0.009038,1.805453,-0.735324,0.512954,0.256300,-1.274853,...,0.197354,0.254250,-0.913514,0.437235,0.950665,1.087089,-0.158040,-0.309794,59.00,0
147633,88773.0,0.481307,0.313129,0.633011,0.903003,-0.050703,0.906784,-0.386907,0.329681,0.401001,...,0.381431,1.342495,0.033959,0.223797,-1.495633,0.007825,0.380752,0.294289,9.99,0
279688,169032.0,-0.175824,1.101026,0.201848,-0.647132,0.397437,-1.112312,1.079160,-0.244948,0.027338,...,-0.282406,-0.528436,0.072211,0.056700,-0.413266,0.139874,0.361310,0.156958,8.07,0

In [23]:
new_data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,...,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000
mean,86829.654472,-2.431489,1.819638,-3.447374,2.247012,-1.525522,-0.681259,-2.800541,0.348288,-1.292938,...,0.359544,0.009450,-0.009944,-0.047734,0.027985,0.029731,0.076702,0.040205,98.159593,0.500000
std,48373.972082,5.488899,3.721108,6.251889,3.211102,4.275718,1.828432,5.863555,4.851836,2.301671,...,2.794168,1.168663,1.166157,0.549496,0.676488,0.468429,1.003408,0.410934,210.848389,0.500254
min,406.000000,-30.552380,-19.653340,-31.103685,-3.519386,-22.105532,-11.561096,-43.557242,-41.044261,-13.434066,...,-22.797604,-8.887017,-19.254328,-2.028024,-4.781606,-1.152671,-7.263482,-1.869290,0.000000,0.000000
25%,44805.250000,-2.788129,-0.145163,-5.113334,-0.181476,-1.789776,-1.551056,-3.105154,-0.169970,-2.279453,...,-0.167462,-0.532236,-0.247518,-0.395785,-0.317367,-0.281223,-0.067878,-0.059922,1.180000,0.000000
50%,78345.500000,-0.937601,0.953698,-1.231392,1.287041,-0.394480,-0.656868,-0.629923,0.179140,-0.715053,...,0.153597,0.028998,-0.039253,0.001724,0.057493,-0.006489,0.046610,0.035067,19.950000,0.500000
75%,133351.250000,0.949687,2.798885,0.383435,4.213453,0.517271,0.075060,0.295546,0.941234,0.170641,...,0.624776,0.594901,0.190727,0.360319,0.403833,0.312212,0.433981,0.218773,99.990000,1.000000
max,172757.000000,2.287359,22.057729,2.972123,12.114672,17.176972,6.474115,5.802537,20.007208,4.301540,...,27.202839,8.361985,5.466230,1.091435,2.721087,2.745261,3.052358,1.779364,2125.870000,1.000000

# Splitting Data Into Feature & Target

In [24]:
X = new_data.drop(columns="Class", axis=1)
Y = new_data["Class"]

In [25]:
print(X.shape, Y.shape)

(984, 30) (984,)

In [26]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.7, random_state=42)

# Building Model

### Model 1 ==> LogisticRegression

In [27]:
log_reg = LogisticRegression(max_iter=2000)
log_reg.fit(x_train, y_train)

train_prediction = log_reg.predict(x_train)
train_score = accuracy_score(y_train, train_prediction)
print(f"The Accurracy Score Of Train model is ==> {train_score}")
print("-"*100)
Test_prediction = log_reg.predict(x_test)
Test_score = accuracy_score(y_test, Test_prediction)
print(f"The Accurracy Score Of Train model is ==> {Test_score}")

The Accurracy Score Of Train model is ==> 0.9302325581395349
----------------------------------------------------------------------------------------------------
The Accurracy Score Of Train model is ==> 0.9324324324324325

## Model 2 ==> RandomForestClassifier

In [28]:
model_RF = RandomForestClassifier(n_estimators=40, max_depth=10)
model_RF.fit(x_train, y_train)

train_prediction_RF = model_RF.predict(x_train)
train_score_RF = accuracy_score(y_train, train_prediction_RF)
print(f"The Accurracy Score Of Train model is ==> {train_score_RF}")
print("-"*100)
Test_prediction_RF = model_RF.predict(x_test)
Test_score_RF = accuracy_score(y_test, Test_prediction_RF)
print(f"The Accurracy Score Of Train model is ==> {Test_score_RF}")

The Accurracy Score Of Train model is ==> 0.9941860465116279
----------------------------------------------------------------------------------------------------
The Accurracy Score Of Train model is ==> 0.9459459459459459

## Model 3 ==> AdaBoostClassifier

In [36]:
Adaboost_reg = AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=100, 
                                                                        min_samples_split=8,
                                                                        min_samples_leaf=4, 
                                                                        random_state=42),
                              n_estimators=5,
                              learning_rate=1)


Adaboost_reg.fit(x_train, y_train)

print(f"The predict Score Train is ==> {Adaboost_reg.score(x_train, y_train)}")
print("%----------------------------------------------------------%")
print(f"The predict Score Test is ==> {Adaboost_reg.score(x_test, y_test)}")

The predict Score Train is ==> 1.0
%----------------------------------------------------------%
The predict Score Test is ==> 0.9256756756756757

## Model 4 ==> XGBClassifier

In [39]:
model_xgb = xgb.XGBClassifier(n_estimators=20, max_depth=10,
                             learning_rate=1,
                             min_child_weight=1, random_state=2,
                             missing=60)
                             
model_xgb.fit(x_train, y_train)

print(f"The predict Score Train is ==> {model_xgb.score(x_train, y_train)}")
print("%----------------------------------------------------------%")
print(f"The predict Score Test is ==> {model_xgb.score(x_test, y_test)}")

The predict Score Train is ==> 1.0
%----------------------------------------------------------%
The predict Score Test is ==> 0.9324324324324325

## Build_System

In [ ]:
input_Data_Prediction = np.asarray( 
                                    list(map(float, input().split(",")))
                                   ).reshape(1, -1)


Prediction = model_xgb.predict(input_Data_Prediction)

print(Prediction)

print()

print("-" * 100)

if Prediction == 1:
    print("The PRediction is ==> Fraud")
else:
    print("The Prediction is ==> Legint")

In [37]:
if Prediction == 1:
    print("The Fraud")
else:
    print("The Legint")

The Fraud

In [82]:
new_date = data[data["Class"] == 1]

new_x = new_date.drop(columns="Class", axis=1)
new_y = new_date["Class"]

ooo = model_xgb.predict(new_x)
predict = accuracy_score(new_y, ooo)

print(predict)

0.9735772357723578

## Over Sampling

In [40]:
X_2 = data.drop(columns="Class", axis=1)
Y_2 = data["Class"]

In [44]:
smote = SMOTE()
print(data[data["Class"]==0].shape[0], data[data["Class"]==1].shape[0])

new_x1, new_y1 = smote.fit_resample(X_2, Y_2)

new_data_Smote = pd.DataFrame(pd.concat([new_x1, new_y1], axis=1))

284315 492

In [47]:
print(new_data_Smote[new_data_Smote["Class"]==0].shape[0], new_data_Smote[new_data_Smote["Class"]==1].shape[0])

284315 284315

In [50]:
x_input = new_data_Smote.drop(columns="Class", axis=1)
y_output = new_data_Smote["Class"]

x_train1, x_test1, y_train1, y_test1 = train_test_split(x_input, y_output, train_size=0.7, random_state=42)

In [53]:
model_xgb = xgb.XGBClassifier(n_estimators=100, max_depth=1000,
                             learning_rate=0.1,
                             min_child_weight=1, random_state=2,
                             missing=60)
                             
model_xgb.fit(x_train, y_train)

The predict Score Train is ==> 0.9999773892639201
%----------------------------------------------------------%
The predict Score Test is ==> 0.9997655182925042

In [57]:
print(f"The predict Score Train is ==> {round(model_xgb.score(x_train1, y_train1), 4)}")
print("%----------------------------------------------------------%")
print(f"The predict Score Test is ==> {round(model_xgb.score(x_test1, y_test1), 4)}")

The predict Score Train is ==> 1.0
%----------------------------------------------------------%
The predict Score Test is ==> 0.9998